### ISSUE TITLE
Should\could I use document.addEventListener in component?

### ISSUE THREAD

**Issue by bubnenkoff** [Lomacar/Ewok#4]
Hi! Could I use `document.addEventListener` in component if I want, for example, create new $store? Or Alpine should do init parts in itself, and components should only use already initialized data?

Or components should not try to touch document.addEventListener and store all data locally?

**Comment by Lomacar** [comment]
I think you could possibly have a reason to do that and it probably can work, although you would need to consider the order that things happen and perhaps other issues. Components will be fully loaded after most other scripts have run.
