### ISSUE TITLE
Cannot read properties of undefined if trying to call component in x-data

### ISSUE THREAD

**Issue by bubnenkoff** [Lomacar/Ewok#5]
Hi! I have got follow component:
```
<script>

function foo() {
    console.log("foo")
    return {}
  }

</script>

<template id="regions-component" noshadow>
 <div x-data="this.props.foo" ></div>
</template>
```
I am getting an error:
```
cdn.min.js:1 Alpine Expression Error: Cannot read properties of undefined (reading 'foo')

Expression: "this.props.foo"
```

What I am doing wrong? 

Am I right understand that if it's store data locally I do not need to mark function as `export`? So I can be able only to call it from itself?

**Comment by Lomacar** [comment]
The script needs to be inside the template, and you need to export the function in order for it to show up in props.
